all:
  hosts:
    cn06:
      ansible_host: 192.168.23.16
      ip: 192.168.23.16
      access_ip: 192.168.23.16
    cn08:
      ansible_host: 192.168.23.18
      ip: 192.168.23.18
      access_ip: 192.168.23.18
    cn05:
      ansible_host: 192.168.23.15
      ip: 192.168.23.15
      access_ip: 192.168.23.15
    cn07:
      ansible_host: 192.168.23.17
      ip: 192.168.23.17
      access_ip: 192.168.23.17
  children:
    kube_control_plane:
      hosts:
        cn05:
    kube_node:
      hosts:
        cn05:
        cn06:
        cn07:
        cn08:
    etcd:
      hosts:
        cn05:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
