all:
  hosts:
    cn01:
      ansible_host: 192.168.23.11
      ip: 192.168.23.11
      access_ip: 192.168.23.11
    cn02:
      ansible_host: 192.168.23.12
      ip: 192.168.23.12
      access_ip: 192.168.23.12
 #   cn03:
 #     ansible_host: 192.168.23.13
 #     ip: 192.168.23.13
 #     access_ip: 192.168.23.13
    cn04:
      ansible_host: 192.168.23.14
      ip: 192.168.23.14
      access_ip: 192.168.23.14
  children:
    kube_control_plane:
      hosts:
        cn01:
    kube_node:
      hosts:
        cn01:
        cn02:
#        cn03:
        cn04:
    etcd:
      hosts:
        cn01:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
